// Pure, environment-agnostic PSL trie: parse the compact binary format and
// run lookups. No I/O, no globals — the byte source is injected by the caller
// (see index.ts), so this module bundles identically for Node and the browser.
//
// The algorithm is a faithful port of the Rust crate's `src/trie.rs`; the two
// are kept byte-identical by the parity suite in `index.test.ts`.

/** Result of a PSL lookup. */
export interface DomainInfo {
  /** The public suffix (e.g. `"co.uk"`, `"com"`, `"github.io"`). */
  readonly suffix: string;
  /** The registrable domain (eTLD+1), or `undefined` if the input is itself a suffix. */
  readonly registrableDomain: string | undefined;
  /** Whether the suffix matched an explicit PSL rule (vs the `*` fallback). */
  readonly known: boolean;
}

/**
 * A node in the PSL trie. `labels[i]` is the edge label to `children[i]`;
 * labels are sorted ascending so lookups binary-search them.
 */
export interface TrieNode {
  readonly suffixBoundary: boolean;
  readonly labels: string[];
  readonly children: TrieNode[];
}

const utf8 = new TextDecoder("utf-8", { fatal: true });

/**
 * Parse the compact binary trie (DFS preorder) into a {@link TrieNode} tree.
 *
 * Format: `[flags:u8] [num_children:u16_le] [child₁ …]`; child:
 * `[label_len:u8] [label_bytes…] [child_node]`. flags bit 0 = suffix boundary.
 *
 * Throws if the data is truncated, mis-sorted, or uses reserved flag bits —
 * the embedded blob is generated by `scripts/build-psl.py`, so a throw here
 * means the package shipped a corrupt artifact.
 */
export function parseTrie(data: Uint8Array): TrieNode {
  const cursor = { pos: 0 };
  const root = parseNode(data, cursor);
  if (cursor.pos !== data.length) {
    throw new Error("PSL data: trailing bytes after root node");
  }
  return root;
}

function parseNode(data: Uint8Array, cursor: { pos: number }): TrieNode {
  const flags = byteAt(data, cursor.pos++);
  // Only bit 0 (suffix boundary) is defined; reject reserved bits.
  if ((flags & ~1) !== 0) {
    throw new Error("PSL data: reserved flag bits set");
  }

  const lo = byteAt(data, cursor.pos++);
  const hi = byteAt(data, cursor.pos++);
  let numChildren = lo | (hi << 8);

  // Guard num_children against the remaining bytes to fail fast on corruption.
  // Each child needs ≥ 5 bytes: label_len(1) + ≥1 label byte + node(3).
  const MIN_CHILD_ENCODED_LEN = 5;
  const remaining = data.length - cursor.pos;
  if (remaining < 0 || numChildren > Math.floor(remaining / MIN_CHILD_ENCODED_LEN)) {
    throw new Error("PSL data: num_children exceeds remaining bytes");
  }

  const labels: string[] = [];
  const children: TrieNode[] = [];
  let prev: string | undefined;

  for (; numChildren > 0; numChildren--) {
    const labelLen = byteAt(data, cursor.pos++);
    // PSL rules cannot produce empty labels.
    if (labelLen === 0) {
      throw new Error("PSL data: empty label");
    }

    const labelEnd = cursor.pos + labelLen;
    if (labelEnd > data.length) {
      throw new Error("PSL data: label runs past end of data");
    }
    const label = decodeLabel(data, cursor.pos, labelEnd);
    cursor.pos = labelEnd;

    // Strictly ascending order is the binary-search invariant.
    if (prev !== undefined && !(label > prev)) {
      throw new Error("PSL data: children not strictly sorted");
    }
    prev = label;

    labels.push(label);
    children.push(parseNode(data, cursor));
  }

  return { suffixBoundary: (flags & 1) !== 0, labels, children };
}

function byteAt(data: Uint8Array, i: number): number {
  if (i >= data.length) {
    throw new Error("PSL data: unexpected end of data");
  }
  return data[i]!;
}

/**
 * Decode a label's UTF-8 bytes to a string.
 *
 * PSL labels are ~96% ASCII (punycode / `a-z0-9-`), so an ASCII fast path via
 * `fromCharCode` skips TextDecoder's per-call overhead and roughly halves parse
 * time; the ~4% of Unicode U-label rules fall back to a real UTF-8 decode.
 */
function decodeLabel(data: Uint8Array, start: number, end: number): string {
  for (let i = start; i < end; i++) {
    if (data[i]! >= 0x80) return utf8.decode(data.subarray(start, end));
  }
  let s = "";
  for (let i = start; i < end; i++) s += String.fromCharCode(data[i]!);
  return s;
}

/**
 * Binary-search a node's children for `label`.
 *
 * Labels are sorted by Rust's `str` ordering (UTF-8 byte lexicographic). For
 * the BMP code points the PSL uses, JS string comparison matches that order,
 * so a plain `<`/`>` comparator is correct.
 */
function indexOfChild(node: TrieNode, label: string): number {
  let lo = 0;
  let hi = node.labels.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const cur = node.labels[mid]!;
    if (cur === label) return mid;
    if (cur < label) lo = mid + 1;
    else hi = mid - 1;
  }
  return -1;
}

function childOf(node: TrieNode, label: string): TrieNode | undefined {
  const i = indexOfChild(node, label);
  return i < 0 ? undefined : node.children[i];
}

function hasChild(node: TrieNode, label: string): boolean {
  return indexOfChild(node, label) >= 0;
}

/**
 * Look up `domain` against the parsed PSL trie.
 *
 * Returns `undefined` for empty input or labels that are empty / the PSL
 * sentinels (`*`, `!prefix`); otherwise always returns a result (unknown TLDs
 * fall back to the implicit `*` rule with `known: false`).
 */
export function lookupTrie(root: TrieNode, domain: string): DomainInfo | undefined {
  const trimmed = domain.trim();
  // Strip a single FQDN-root trailing dot (multiple dots are left to fail below).
  const stripped = trimmed.endsWith(".") ? trimmed.slice(0, -1) : trimmed;
  if (stripped === "") return undefined;

  // Labels TLD-first, mirroring Rust's `rsplit('.')`.
  const labels = stripped.split(".").reverse();

  // Reject empty labels (leading/consecutive dots) and sentinel labels that
  // name internal trie nodes (`*`, `!…`) so callers cannot walk them directly.
  for (const label of labels) {
    if (label === "" || label === "*" || label.startsWith("!")) return undefined;
  }

  let node = root;
  let suffixDepth = 0;
  let known = false;

  for (let depth = 0; depth < labels.length; depth++) {
    const label = labels[depth]!.toLowerCase();

    // Record a wildcard match as a fallback BEFORE the exact match, so the
    // wildcard is not shadowed by a non-boundary exact child on the same path.
    if (hasChild(node, "*")) {
      // An exception rule (`!label`) cancels the wildcard for this label only.
      if (hasChild(node, "!" + label)) {
        suffixDepth = depth;
      } else {
        suffixDepth = depth + 1;
      }
      known = true;
    }

    // Exact match — descend for potentially more specific rules.
    const child = childOf(node, label);
    if (child !== undefined) {
      if (child.suffixBoundary) {
        suffixDepth = depth + 1;
        known = true;
      }
      node = child;
      continue;
    }

    // No exact match — any wildcard was already recorded above.
    break;
  }

  if (suffixDepth === 0) {
    // No rule matched — prevailing `*` rule: the TLD is the suffix.
    suffixDepth = 1;
    known = false;
  }

  const suffix = labels
    .slice(0, suffixDepth)
    .reverse()
    .map((l) => l.toLowerCase())
    .join(".");

  const registrableDomain =
    labels.length > suffixDepth ? `${labels[suffixDepth]!.toLowerCase()}.${suffix}` : undefined;

  return { suffix, registrableDomain, known };
}
